module.exports = [
    "Refrigerator",
    "Freezer",
    "Oven",
    "Stove",
    "Microwave",
    "Dishwasher",
    "Washing Machine",
    "Dryer",
    "Air Conditioner",
    "Heater",
    "Humidifier",
    "Dehumidifier",
    "Vacuum Cleaner",
    "Iron",
    "Toaster",
    "Coffee Maker",
    "Blender",
    "Juicer",
    "Food Processor",
    "Mixer",
    "Electric Grill",
    "Electric Griddle",
    "Slow Cooker",
    "Rice Cooker",
    "Bread Maker",
    "Ice Cream Maker",
    "Popcorn Maker",
    "Electric Kettle",
    "Hair Dryer",
    "Electric Toothbrush",
    "Electric Shaver",
    "Massager"
  ];
  